### ISSUE TITLE
[5/29] Latest updates to issue 1437_district_heating_cooling break GMT

### ISSUE THREAD

**Issue by nllong** [urbanopt/geojson-modelica-translator#105]
To recreate

* checkout the latest version of the `issue1437_district_heating_cooling` branch of MBL
* Make sure that MODELICAPATH is set to the correct MBL directory
* Make sure docker is running (simulations run in Docker)
* run `py.test` on latest develop of GMT or run a specific Spawn model for expediency (`py.test tests/model_connectors/test_spawn.py::SpawnModelConnectorSingleBuildingTest::test_spawn_to_modelica_and_run`)
* Results will be in the `geojson-modelica-translator/tests/model_connectors/output/spawn_single_results` folder

```
[INFO][FMILIB] Loading 'linux64' binary with 'default' platform types
EnergyPlus Starting
EnergyPlus, Version 9.3.0-278a3caa5c, YMD=2020.05.18 15:21
**FATAL:Errors occurred on processing input file. Preceding condition(s) cause termination.
EnergyPlus Run Time=00hr 00min  0.16sec
Program terminated: EnergyPlus Terminated--Error(s) Detected.
```

**Comment by AntoineGautier** [comment]
This is fixed by checking out `Buildings/Resources/Data/ThermalZones/EnergyPlus/Validation/RefBldgSmallOffice/RefBldgSmallOfficeNew2004_Chicago.idf` from MBL. 
I propose that this file be included as a dependency for testing as it is likely to be updated with ulterior releases of EnergyPlus.
I also noticed that `requirements.txt` used the published version of BuildingsPy. Best would be to use rather the GitHub master.
