### ISSUE TITLE
CU to Review Scaling Factors

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#175]
wait until Antione is back

**Comment by Helarga** [comment]
- time series model with modifications to avoid  the trial and error approach to set the correct  facScaHea and facScaCoo
https://github.com/Helarga/modelica-buildings/blob/issue1437_district_heating_cooling/Buildings/Applications/DHC/Loads/Examples/BaseClasses/BuildingTimeSeriesHE.mo

- example 1 ( the same example developed by LBL but with a  facScaHea = facScaHea=1)
https://github.com/Helarga/modelica-buildings/blob/issue1437_district_heating_cooling/Buildings/Applications/DHC/Loads/Examples/CouplingTimeSeriesHE.mo

- example 2 ( time series simultaneous heating and cooling loads generated by OS )
https://github.com/Helarga/modelica-buildings/blob/issue1437_district_heating_cooling/Buildings/Applications/DHC/Loads/Examples/TimeSeriesOpenStudioSimultaneousHeatingCooling.mo

**Comment by JingWang-CUB** [comment]
@Helarga Thank you for sending the models for us to review. After reviewing the `BuildingTimeSeriesHE` model, I have a few questions and comments. Please see below.

1. I understand that you set the scaling factors for both heating and cooling to 1 and use cp_air and deltaT for mass flow rate calculation instead. This seems to be a good approach. Could you please remind me why originally scaling factors were needed? 

2. cp_air should be an inner parameter that's calculated depending on the state of the medium (air).

Otherwise, the model looks good to me. Thanks!

**Comment by Helarga** [comment]
> @Helarga Thank you for sending the models for us to review. After reviewing the `BuildingTimeSeriesHE` model, I have a few questions and comments. Please see below.
> 
> 1. I understand that you set the scaling factors for both heating and cooling to 1 and use cp_air and deltaT for mass flow rate calculation instead. This seems to be a good approach. Could you please remind me why originally scaling factors were needed?

> **please, check the original models in**  
> Buildings.Applications.DHC.Loads.Examples.CouplingTimeSeries and 
> Buildings.Applications.DHC.Loads.Examples.BaseClasses.BuildingTimeSeries
 **if there is something not clear for you, contact me**

> 2. cp_air should be an inner parameter that's calculated depending on the state of the medium (air).

> **no it shouldn't,** the cp_air parameter = 1.005kJ/kg is a very good nominal specific heat capacity value for nominal air temperature of heating =20degC and cooling =24degC..

https://www.ohio.edu/mechanical/thermo/property_tables/air/air_Cp_Cv.html#:~:text=The%20nominal%20values%20used%20for,one%20can%20obtain%20significant%20errors.

**you can also run this nice model at the MBL and check how the cp value change with air temperature 
Buildings.Media.Examples.AirDerivativeCheck**

**you can also find that, specific heat capacity is evaluated as constant =1006 in 
Buildings.Utilities.Psychrometrics.Constants**
and used here 
**Buildings.Air.Systems.SingleZone.VAV.ChillerDXHeatingEconomizer**
and here also
**Buildings.Controls.OBC.CDL.Psychrometrics.h_TDryBulPhi**
 
Otherwise, the model looks good to me. Thanks!

**Comment by nllong** [comment]
Hi @JingWang-CUB -- thanks for reviewing. When you are updating the partial building models per our other discussions can you also update the scaling factor as recommended?

**Comment by JingWang-CUB** [comment]
Hi @nllong , the two versions seem to be just different ways of model design. Should we also get @JayHuLBL 's feedback and agree on one version of the BuildingTimeSeries model? Thank you!
