### ISSUE TITLE
[12/1/20] Development of GeoJSON file and system param file for CU Boulder

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#218]

**Comment by mingzhe37** [comment]
Hi @laurenklun, could you please give more detailed requirements for these files? @nllong @JingWang-CUB @khinkelman

**Comment by nllong** [comment]
In order to run the GMT, both a GeoJSON file and System Param file need to be developed. [This file](https://github.com/urbanopt/cu-pilot-project/blob/develop/cu_boulder.geojson) needs to be updated to be the buildings that are to be modeled on the campus. And [this file](https://github.com/urbanopt/cu-pilot-project/blob/develop/cu_boulder_system_params.json) needs to include the loads of the buildings that are going to be modeled. 

We need to decide on how the loads are going to be modeled. I suggest starting with time series (\dot{m} \Delta T).

**Comment by mingzhe37** [comment]
Hi Nick, thank you for your reply! Yes, we have the time series load data, so we plan to start with the time series model. 
By the way, in order to verify that the geojson and system parameter input files are created correctly based on schemas, I guess it would be necessary to test in GMT. Do you think it is necessary for me to do this? or you can test them afterward?

**Comment by nllong** [comment]
Yes, you definitely have to test through the GMT.

**Comment by mingzhe37** [comment]
Got it. For now, my plan is to create a simple generic case that includes a time series load model, a district system, and some connectors to test whether this configuration works. If this goes well, I can update the parameters to the CU case study's parameters and can verify them anytime. Do you have thoughts on this way of testing?
