### ISSUE TITLE
Update TEASER Model's TAir addition

### ISSUE THREAD

**Issue by nllong** [urbanopt/geojson-modelica-translator#300]
Update the added TAir to the generated TEASER model to protect against singularity issue. 

The block needs to have the `ATot` and `VAir` protection. [This](https://github.com/urbanopt/geojson-modelica-translator/blob/develop/geojson_modelica_translator/model_connectors/load_connectors/teaser.py#L315) is where the TAir is added.

```Modelica
  Modelica.Blocks.Interfaces.RealOutput TAir(
    final quantity="ThermodynamicTemperature",
    final unit="K",
    displayUnit="degC") if ATot > 0 or VAir > 0 "Indoor air temperature"
    annotation (Placement(transformation(extent={{240,150},{260,170}}),
    iconTransformation(extent={{240,150},{260,170}})));
```

**Comment by vtnate** [comment]
@nllong I have a couple questions/concerns about this:
- `ATot` and `VAir` aren't declared anywhere in the GMT. I've tried several different forms of the `if` statement but the test still fails due to that.
- Michael's code looks similar to what we have in `CoolingIndirect.mot`, not the output generated by `teaser.py`:

>   Buildings.Controls.OBC.CDL.Interfaces.RealOutput TAir(
quantity="ThermodynamicTemperature",
unit="K",
displayUnit="degC") if ATot > 0 or VAir > 0 "Room air temperature"
annotation(Placement(transformation(extent={{100,38},{120,58}})));

- We only have a test for [teaser_single](https://github.com/urbanopt/geojson-modelica-translator/blob/develop/tests/model_connectors/test_teaser.py#L62), does that mean we should write another test for the condition Michael is referring to in his email?

**Comment by nllong** [comment]
You can add a conditional statement to the `add_parameter` method. It will be just a string. See [this line](https://github.com/urbanopt/geojson-modelica-translator/blob/39440806bebfb32235cdb5a62f5769886be2181e/geojson_modelica_translator/model_connectors/load_connectors/teaser.py#L318)

Nah, I don't think we need another test. This will change all the TEASER Modelica files, which is what needs to happen.

**Comment by vtnate** [comment]
Yeah, that's what I did, which produced the output shown above, and lead to the test failing because `ATot` and `VAir` aren't declared anywhere.

**Comment by nllong** [comment]
OOOOHH. I get you now! Thanks for the patience there.

So I think it gets more complicated. It looks like that the `ATot` and `VAir` is in the RC model. So it would be `{thermal_zone_name}.ATot` and `{thermal_zone_name}.VAir`. But notice in the code that the `thermal_zone_name` var is not defined adding the TAir output. So you'll need to move some stuff around. 

And I'm only 80% sure that this will work.

**Comment by nllong** [comment]
@mwetter -- this has been updated: https://github.com/urbanopt/geojson-modelica-translator/blob/develop/geojson_modelica_translator/model_connectors/load_connectors/teaser.py#L355-L364
