### ISSUE TITLE
Fix heating q flow for TimeSeries district system

### ISSUE THREAD

**Issue by macintoshpie** [urbanopt/geojson-modelica-translator#311]
### Expected Behavior
CVRMSD for time series load and heating indirect q flow should be less than 30% (per ASHRAE Guildeline 14).

### Actual Behavior
CVRMSD appears to be greater than 200%. See comments following this one here: https://github.com/urbanopt/geojson-modelica-translator/pull/305#issuecomment-780186111

### Steps to Reproduce
Run `tests/model_connectors/test_district_heating_and_cooling_systems.py`

**Comment by amyeallen1** [comment]
Hi Ted (and Nick as an FYI), @macintoshpie, @nllong , 
   After further investigation, I realize that this discrepancy is due to the fact that the "Q_flow" associated with the ETS is measured on the district side, while the "Q_HeaFlow" and "Q_CooFlow" associated with the load is measured on the load side. With the cooling load, they happened to be similar, but with a different configuration in terms of district side and load side delta T for the heating case, they were not. Sorry--this was my fault for saying that we should compare those two values. 

   To evaluate if the loads are being met, we should compare the "QReqCoo_Flow" and "QCoo_Flow" and "QReqHea_Flow" and "QHea_Flow" associated with the load itself. Here's a plot showing an example of this comparison. I looked at this for heating and cooling for the two loads in this example, and the load seems to generally be met. There might be some room for refinement in terms of the controller. 

![image](https://user-images.githubusercontent.com/23225173/112882974-e3ffa280-908a-11eb-9946-1ad1529c63f0.png)


   Ted, could you please revise the test file to reflect this when you have a chance? No rush. Thanks!

**Comment by nllong** [comment]
Looks better--still have some weird control issues, but the NMBE and CVRMSE should be much better.

**Comment by amyeallen1** [comment]
Yes, are there any systematic approaches to improve the controller performance beyond manual tuning? Maybe this could be an item for discussion with our LBL/CU colleagues to see if they have any advice? @nllong
