### ISSUE TITLE
Add simulation support for windows

### ISSUE THREAD

**Issue by macintoshpie** [urbanopt/geojson-modelica-translator#360]
### Expected Behavior
You should be able to run simulations (using our jmodelica/docker setup) on windows.

### Actual Behavior
You cannot.

### Steps to Reproduce
If you have access to a windows machine, try running one of the tests marked with the `simulation` tag. Else check on GH actions

**Comment by macintoshpie** [comment]
I tried changing the script to python for starting docker, which runs ok for unix, but once it gets to running the container it fails:
```
Unable to find image 'michaelwetter/ubuntu-1804_jmodelica_trunk:latest' locally
latest: Pulling from michaelwetter/ubuntu-1804_jmodelica_trunk
docker: image operating system "linux" cannot be used on this platform.
See 'docker run --help'.
```

We might be out of luck for now, looks like the windows server vm we're using won't allow us to run linux containers: https://github.com/actions/virtual-environments/issues/1143

Our other options are to setup our own runner, skip the simulation tests for windows, or stub out `docker` on windows.

Maybe someone with access to a real windows machine can provide some help here as to whether or not our simulation will work?

**Comment by vtnate** [comment]
LadyBug Tools can't include the GMT in their tool without running these simulations. One other potential alternative could be to set up the simulations as a hosted service, kinda like REopt Lite.

Which of these options sucks the least is the hard part.

**Comment by macintoshpie** [comment]
This is an issue for running linux containers on windows in general. The user will have to make sure their system is setup properly: https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers

We definitely won't be able to run it in our CI for now from what I've read.

Technically this is "not our problem" but maybe we could find a way to make it easier for windows users?

**Comment by macintoshpie** [comment]
After a bit of research it sounds like it's fairly straightforward for desktop users, windows 10 pro is the easiest to get setup, and other versions are doable: https://docs.docker.com/docker-for-windows/install/#hyper-v-backend-and-windows-containers

**Comment by chriswmackey** [comment]
Ah, we faced this problem really badly when we built a plugin for [OpenFOAM](https://www.openfoam.com/), which also relied on Docker to be run on Windows. Almost all of the architecture and engineering industry uses Windows and, at the time, Windows 7 was the dominant version so everyone except a handful of users were unable to get it installed. We taught a workshop on our OpenFOAM plugin and it was practically a miracle that we got OpenFOAM with docker correctly installed on 12 Windows machines after ~4 hours of work.

In the end, the only thing that solved the situation was by switching over to [Blue CFD](http://bluecfd.github.io/Core/), which is a native Windows port of OpenFOAM. I am hopeful that more users could use the docker route now that Windows 10 is the dominant version. But I am sure that, while researchers should be able to get docker set up correctly, its probably not something you can expect from a typical architecture or engineering practice.

I understand that you have to do what you have to do for now and, if the GMT is primarily something that researchers use for the immediate future, then so be it. You can still count on me to get docker working on my Windows machine and take the hour or so that it might take SOM to get it running on their end. But I sense that the only things that will make the GMT something that the wider industry can use are either:
1. A native Windows solution similar to Blue CFD.
2. A could service where users did not have to worry about having docker installed.

The latter is our main business model at Ladybug Tools so we should be able to help here but we will charge people for it. If you were to set up a free service like that for REop Lite, how would you pay for the computing? Or will you limit the computing usage per user somehow?
