### ISSUE TITLE
Using medium model from MBL

### ISSUE THREAD

**Issue by AntoineGautier** [urbanopt/geojson-modelica-translator#38]
TEASER models generated when running `pytest` (e.g. `tests/output/geojson_1/Loads/B5a6b99ec37f4de7f94020090/ICT.mo`) use different medium models than the ones from MBL. Especially `Modelica.Media.Air.DryAirNasa` is not suited for moisture modeling.

### Expected Behavior

```
  Buildings.ThermalZones.ReducedOrder.RC.TwoElements
  thermalZoneTwoElements(
    redeclare package Medium = Buildings.Media.Air,
```

### Actual Behavior

```
  Buildings.ThermalZones.ReducedOrder.RC.TwoElements
  thermalZoneTwoElements(
    redeclare package Medium = Modelica.Media.Air.DryAirNasa,
```

### Steps to Reproduce

Run `pytest`

### Version Information

TEASER: `URBANopt/0.7.2
`

**Comment by vtnate** [comment]
The `Modelica.Media.Air.DryAirNasa` model is no longer present in `thermalZoneTwoElements` and is still present in `thermalZoneFourElements`. Is this the expected behavior?

We do not explicitly make any changes to this line of the teaser model at this time.

@nllong Can this issue be safely closed?
