### ISSUE TITLE
V9 Upgrade

### ISSUE THREAD

**Issue by laurenklun** [urbanopt/geojson-modelica-translator#409]
Compiler issue is interfering with work on this

Potential options to address this for compilation: 
1) a. Dymola? For one-off tests/POC 
b. Should work in the short term. (preferred til Spawn compiler fully integrated) 
2. Ask Modelon for Optimica license for Nate
(can set up CI for that mac address)
3. run in a container 
Full simulation running ability for Spawn is a ways off. PyFMI for simulation in the meantime. 

Solver dependencies were a hiccup with simulation of certain Spawn FMUs in PyFMI. 

Nick can take on compiler tasks. 

Zahra working on writing two basic tests
1. time series w/ no simulation 
2. time series w/ heating indirect w/ simulation 

Upgrade branch of MBL that is in the GMT to V8. 

Wrote a scrip to organize/categorize errors.

Ted to connect with Zahra as she is currently blocked.

see google doc 
https://docs.google.com/document/d/1XADCxfyVe3KW9SW7YX0q7UmsQFAjtz2s_8Efak4LU48/edit?usp=sharing

Could be used towards a GED project deliverable. 

Necessary for 5GDHC models. 

With support from Nick, possible to finish in Q2 22

Kyle requested PSU team to add parameter mapping to spreadsheet

Scripts are okay; need to address frozen CW hiccup. Jiazhen to consider better parameterization of initial values. 

Won't work with JModelica. Optimica will facilitate this. 

District models working. 

A hiccup now with dist line models. Try with previous version of MBL? Seeking advice from Mingzhe as well. 

PR under review by Nick and Amy.

**Comment by nllong** [comment]
The model appears to be working as expected. Notes from Jiazhen:
1.	IMO, the script used to generate the Modelica models works properly
2.	The reason 4G Modelica models did not work was due to equipment sizing: the chiller selected was too big and the cooling tower bypass valve did not bypass enough water flow and caused freezing when ambient temperature is too low.
3.	Both issues in Point 2 has been addressed and I have shown the results of 365 day simulation.
